manager:
  subnet_prefixes: 172.20.,10.0.,192.168.

etcd:
  host: 127.0.0.1
  port: 2379
  enable_auth: false
  user: root
  password: password
pixel:
  streaming:
    ip: 127.0.0.1
signal:
  server:
    url: http://127.0.0.1
max:
  instances: 5
startup:
  instances: 3
default:
  d3d:
    renderer: d3d11
